### ISSUE TITLE
Doesn't seem to work with Sublime Text

### ISSUE THREAD

**Issue by chenglou** [freebroccolo/ocaml-language-server#26]
I've tried with https://github.com/sourcegraph/sublime-lsp

My SublimeLsp.sublime-settings:

```json
{
  "clients": [
    {
      "binary": "ocaml-language-server",
      "args": ["--stdio"],
      "file_exts": ["ml", "mli", "re", "rei"],
      "path_additions": ["/usr/local/bin"]
    }
  ]
}
```

`[Errno 32] Broken pipe` in the sublime console

**Comment by freebroccolo** [comment]
Did you manage to get any of the other language servers to work with that plugin? I tried awhile back and didn't have any luck (I think I tried the typescript and go servers) but since I don't use Sublime much I wasn't sure if it was just a problem on my end. I'll try to take a look at it again though.

**Comment by frou** [comment]
sourcegraph's language server client for Sublime seems to be abandoned. There is a new client under active development here: https://github.com/tomv564/LSP

**Comment by bsansouci** [comment]
Getting
```
LSP: notify: textDocument/didChange 
LSP: client unexpectedly died: [Errno 32] Broken pipe 
```
After fixing this
```
LSP: starting in /Users/sansouci/Desktop/reasonglexampleproject 
LSP: starting ['ocaml-language-server', '--stdio'] 
LSP: client registered for window 4 {'reason': <LSP.main.Client object at 0x10db71710>} 
LSP: notify: textDocument/didOpen 
LSP: (stderr):  /usr/local/lib/node_modules/ocaml-language-server/out/src/server/processes/merlin.js:9 
LSP: (stderr):  this.readline.question(JSON.stringify(task), _.flow(JSON.parse, callback)); 
LSP: (stderr):  ^ 
LSP: (stderr):   
LSP: (stderr):  TypeError: Cannot read property 'question' of undefined 
LSP: (stderr):  at Merlin.queue.async.priorityQueue (/usr/local/lib/node_modules/ocaml-language-server/out/src/server/processes/merlin.js:9:26) 
LSP: (stderr):  at /usr/local/lib/node_modules/ocaml-language-server/node_modules/async/dist/async.js:3894:5 
LSP: (stderr):  at process (/usr/local/lib/node_modules/ocaml-language-server/node_modules/async/dist/async.js:2309:17) 
LSP: (stderr):  at Immediate.<anonymous> (/usr/local/lib/node_modules/ocaml-language-server/node_modules/async/dist/async.js:2115:16) 
LSP: (stderr):  at runCallback (timers.js:672:20) 
LSP: (stderr):  at tryOnImmediate (timers.js:645:5) 
LSP: (stderr):  at processImmediate [as _immediateCallback] (timers.js:617:5) 
```
by setting `"ocamlmerlin"` in settings to an absolute path.

**Comment by freebroccolo** [comment]
@bsansouci I think the second part that required the absolute path might be due to a regression from #29. Need to investigate. Not sure about the broken pipe though. When I tried the emacs client I didn't see that as far as I remember.

Do the other language servers work okay with that plugin for you?

**Comment by bsansouci** [comment]
It started off with 
```
LSP: starting ['javascript-typescript-stdio'] 
LSP: client registered for window 7 {'jsts': <LSP.main.Client object at 0x10d21d7d0>} 
LSP: notify: textDocument/didOpen 
LSP: got json:  {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"textDocumentSync":1,"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true, 
LSP: error handling response 1 
LSP: Error handling server content:  
```

But then I write some stuff and hovering worked and type inference worked (with docs for example about `console.log`). I don't know about all of the capabilities of the JS one but seems like there was some communication going on.

**Comment by bsansouci** [comment]
Ok I just tried by hardcoding ocamlmerlin's path into the JS of the plugin and called `initialize` inside the constructor of the `merlin` class.
Here's the full logs:
```
LSP: no clients found for window 18 
LSP: no clients found for window 18 
LSP: starting in /Users/sansouci/Desktop/reasonglexampleproject 
LSP: starting ['ocaml-language-server', '--stdio'] 
LSP: client registered for window 18 {'reason': <LSP.main.Client object at 0x10db89810>} 
LSP: notify: textDocument/didOpen 
LSP: got json:  {"jsonrpc":"2.0","id":0,"method":"reason.client.giveTextDocument","params":{"text":"module Layout = Draw.Layout;\n\nmodule Node = Draw.Node;\n\nlet font7 = Font.loadFont fontSize::7. fontPath::\"asset 
LSP: Unhandled request reason.client.giveTextDocument 
LSP: got json:  {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":true},"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"definit 
LSP: error handling response 1 
LSP: Error handling server content:  
SublimeLinter: reason: Child1.re ['/Users/sansouci/Desktop/reason/_build/bin/refmt', '-use-stdin', 'true', '-parse', 're', '-is-interface-pp', 'false', '/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re', '-print', 'none'] 
LSP: got json:  {"jsonrpc":"2.0","id":1,"method":"reason.client.giveTextDocument","params":{"uri":"file:///Users/sansouci/Desktop/reasonglexampleproject/node_modules/ReasonglInterface/lib/ocaml/bytecode/ReasonglInter 
LSP: Unhandled request reason.client.giveTextDocument 
LSP: got json:  {"jsonrpc":"2.0","id":2,"method":"reason.client.giveWordAtPosition","params":{"position":{"character":6,"line":14},"uri":"file:///Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re"}} 
LSP: Unhandled request reason.client.giveWordAtPosition 
LSP: got json:  {"jsonrpc":"2.0","id":3,"method":"reason.client.giveWordAtPosition","params":{"position":{"character":0,"line":14},"uri":"file:///Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re"}} 
LSP: Unhandled request reason.client.giveWordAtPosition 
SublimeLinter: reason: Child1.re ['/Users/sansouci/Desktop/reason/_build/bin/refmt', '-use-stdin', 'true', '-parse', 're', '-is-interface-pp', 'false', '/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re', '-print', 'none'] 
SublimeLinter: reason: Child1.re ['/Users/sansouci/Desktop/reason/_build/bin/refmt', '-use-stdin', 'true', '-parse', 're', '-is-interface-pp', 'false', '/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re', '-print', 'none'] 
LSP: notify: textDocument/didChange 
SublimeLinter: reason: Child1.re ['/Users/sansouci/Desktop/reason/_build/bin/refmt', '-use-stdin', 'true', '-parse', 're', '-is-interface-pp', 'false', '/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re', '-print', 'none'] 
SublimeLinter: reason output:
File "/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re", line 68, characters 0-6:
Error: 1727: Incomplete statement. Did you forget a ";"? 
LSP: notify: textDocument/didChange 
SublimeLinter: reason: Child1.re ['/Users/sansouci/Desktop/reason/_build/bin/refmt', '-use-stdin', 'true', '-parse', 're', '-is-interface-pp', 'false', '/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re', '-print', 'none'] 
SublimeLinter: reason output:
File "/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re", line 68, characters 0-6:
Error: 1727: Incomplete statement. Did you forget a ";"? 
LSP: notify: textDocument/didChange 
SublimeLinter: reason: Child1.re ['/Users/sansouci/Desktop/reason/_build/bin/refmt', '-use-stdin', 'true', '-parse', 're', '-is-interface-pp', 'false', '/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re', '-print', 'none'] 
SublimeLinter: reason output:
File "/Users/sansouci/Desktop/reasonglexampleproject/src/Child1.re", line 68, characters 0-6:
Error: 1727: Incomplete statement. Did you forget a ";"? 
LSP: notify: textDocument/didChange 
```

I load the file called Child1.re, I hover over two things and then write `print_endline`.

I have no idea what those messages mean, is that unhandled stuff on LSP's side?

**Comment by freebroccolo** [comment]
@bsansouci Are you using the release version of the server or building from `master`? I believe the part about unhandled `reason.client.giveTextDocument` and `reason.client.giveWordAtPosition` refers to an older custom message that the server required clients to implement but it is no longer needed if you build the server from `master`.

So maybe it will work if you can try directly from the `master` branch.

**Comment by chenglou** [comment]
Master works on ST! Closing this issue, thanks @frou!

@freebroccolo would it be possible to make a new release?

**Comment by bsansouci** [comment]
Works here too!
