### ISSUE TITLE
Crash on didChangeConfiguration with empty settings

### ISSUE THREAD

**Issue by rymdhund** [freebroccolo/ocaml-language-server#66]
The latest nvim language client is sending a 'workspace/didChangeConfiguration' with the settings parameter set to {}. This causes the server to crash:

```
/usr/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:14
                if (this.session.settings.reason.diagnostics.merlinPerfLogging) {
                                                 ^

TypeError: Cannot read property 'diagnostics' of undefined
    at logMessage (/usr/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:14:50)
    at /usr/lib/node_modules/ocaml-language-server/node_modules/lodash/lodash.js:5157:35
    at Interface._onLine (readline.js:280:5)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
```

See this issue for more details: https://github.com/autozimu/LanguageClient-neovim/issues/183

**Comment by rseymour** [comment]
I had the same bug as well on mac.

**Comment by abs-zero** [comment]
I have the same problem in neovim in linux. Any workaround for this?

**Comment by freebroccolo** [comment]
I just uploaded a new release (`1.0.15`) which should fix this issue.
