### ISSUE TITLE
Cannot read property 'diagnostics' of undefined with empty config

### ISSUE THREAD

**Issue by DeltaEvo** [freebroccolo/ocaml-language-server#67]
```
/usr/local/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:14 if (this.session.settings.reason.diagnostics.merlinPerfLogging) {
                                                 ^

TypeError: Cannot read property 'diagnostics' of undefined
    at logMessage (/usr/local/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:14:50)
    at /usr/local/lib/node_modules/ocaml-language-server/node_modules/lodash/lodash.js:5157:35
    at Interface._onLine (readline.js:280:5)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
```
When LanguageClient-neovim send an empty json as config
Related https://github.com/autozimu/LanguageClient-neovim/issues/183

**Comment by DeltaEvo** [comment]
I have been too slow ... so it's a duplicate of #66
